server:
  port: 3333
  servlet:
    context-path: /
spring:
  application:
    name: shopping
    #实现WebMvcConfigurer后 配置文件内容会失效
  cache:
    type: redis
    redis:
      cache-null-values: true
    cache-names: sku,flash-sale-sku,flash-sale-mq-list
  redis:
    database: 1
    host: localhost
    port: 6379
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 回调类型
    publisher-confirm-type: correlated
    # 开启回调
    publisher-returns: true
    listener:
      type: simple
      simple:
        #手动确认-设置后失效
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
          max-attempts: 3
          # 时间策略因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
          # 无状态重试
          stateless: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 10
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
      # Destroy 线程会检测连接的间隔时间，如果连接空闲时间大于等于 minEvictableIdleTimeMillis 则关闭物理连接。
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的 sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      validationQuery: SELECT 1
      # 建议配置为 true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      # 是否自动回收超时连接
      removeAbandoned: true
      # 超时时间 (以秒数为单位)
      remove-abandoned-timeout: 180
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.sunjutou.shopping.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
my-config:
  # 加密密钥
  token-secret: sanjutou
  #过期时间/天
  expires-time: 7
  # 静态路径前缀
  resource-prefix: http://localhost:3333/
logging:
  file:
    name: /data/shopping.log
  level:
    root: info